height = float(input("Enter your height (m): "))
weight = float(input("Enter your weight (kg): "))
bmi = (weight) / (height ** 2) 
is_underweight = (bmi >= 0) and (bmi <= 18.4)
is_normalweight = (bmi >18.4) and (bmi <= 24.9)
is_overweight = (bmi > 24.9) and (bmi <= 29.9)
is_obese = (bmi > 29.9) and (bmi <= 34.9)
print(f"BMI value: {bmi: .2f}")
print(f"Underweight: {is_underweight}")
print(f"Normalweight: {is_normalweight}")
print(f"Overweight: {is_overweight}")
print(f"Obese: {is_obese}")